server:
  port: 8080

customer:
  url: http://customer-app:8081
product:
  url: http://product-app:8082

spring:
  test:
    database:
      replace: none
  jpa:
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:mysql://credit-db:3306/CreditDB?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: credit_user
    password: 'credit_pass'
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 28000
      validation-timeout: 28000